steps:
  - name: create app.yaml
    entrypoint: bash
    args:
      - -c
      - ./app.yaml.sh
      - ">"
      - app.yaml
    secretEnv:
      - ADYEN_API_KEY_VAR
      - ADYEN_CLIENT_KEY_VAR
      - OAUTH_CLIENT_SECRET_VAR
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args:
      - -c
      - gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy
timeout: 1600s
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ADYEN_API_KEY_VAR/versions/1
      env: ADYEN_API_KEY_VAR
    - versionName: projects/$PROJECT_ID/secrets/ADYEN_CLIENT_KEY_VAR/versions/1
      env: ADYEN_CLIENT_KEY_VAR
    - versionName: projects/$PROJECT_ID/secrets/OAUTH_CLIENT_SECRET_VAR/versions/1
      env: OAUTH_CLIENT_SECRET_VAR