steps:
  - name: golang:1.20
    entrypoint: /bin/bash
    args:
      - -c
      - |
        go install github.com/jstemmer/go-junit-report/v2@latest
        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: bash
    args: ['-c', './app.yaml.sh > ./app.yaml && gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy']
    secretEnv:
      - ADYEN_API_KEY_VAR
      - ADYEN_CLIENT_KEY_VAR
      - ADYEN_OAUTH_CLIENT_SECRET_VAR
      - STRIPE_OAUTH_CLIENT_SECRET_VAR
      - STRIPE_API_KEY_VAR
      - MOLLIE_API_KEY_VAR
      - MOLLIE_OAUTH_CLIENT_SECRET_VAR
timeout: 1600s

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/ADYEN_API_KEY_VAR/versions/latest
      env: ADYEN_API_KEY_VAR
    - versionName: projects/$PROJECT_ID/secrets/ADYEN_CLIENT_KEY_VAR/versions/latest
      env: ADYEN_CLIENT_KEY_VAR
    - versionName: projects/$PROJECT_ID/secrets/ADYEN_OAUTH_CLIENT_SECRET_VAR/versions/latest
      env: ADYEN_OAUTH_CLIENT_SECRET_VAR
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_API_KEY_VAR/versions/latest
      env: STRIPE_API_KEY_VAR
    - versionName: projects/$PROJECT_ID/secrets/STRIPE_OAUTH_CLIENT_SECRET_VAR/versions/latest
      env: STRIPE_OAUTH_CLIENT_SECRET_VAR
    - versionName: projects/$PROJECT_ID/secrets/MOLLIE_API_KEY_VAR/versions/latest
      env: MOLLIE_API_KEY_VAR
    - versionName: projects/$PROJECT_ID/secrets/MOLLIE_OAUTH_CLIENT_SECRET_VAR/versions/latest
      env: MOLLIE_OAUTH_CLIENT_SECRET_VAR

# Save test logs to Google Cloud Storage
artifacts:
  objects:
    location: gs://marcsexperiment.appspot.com  
    paths:
      - ${SHORT_SHA}_test_log.xml   