// Code generated by MockGen. DO NOT EDIT.
// Source: payer.go

// Package checkoutstripe is a generated GoMock package.
package checkoutstripe

import (
	context "context"
	reflect "reflect"

	stripe "github.com/stripe/stripe-go/v74"
	gomock "go.uber.org/mock/gomock"
)

// MockPayer is a mock of Payer interface.
type MockPayer struct {
	ctrl     *gomock.Controller
	recorder *MockPayerMockRecorder
}

// MockPayerMockRecorder is the mock recorder for MockPayer.
type MockPayerMockRecorder struct {
	mock *MockPayer
}

// NewMockPayer creates a new mock instance.
func NewMockPayer(ctrl *gomock.Controller) *MockPayer {
	mock := &MockPayer{ctrl: ctrl}
	mock.recorder = &MockPayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayer) EXPECT() *MockPayerMockRecorder {
	return m.recorder
}

// CreateCheckoutSession mocks base method.
func (m *MockPayer) CreateCheckoutSession(ctx context.Context, params stripe.CheckoutSessionParams) (stripe.CheckoutSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckoutSession", ctx, params)
	ret0, _ := ret[0].(stripe.CheckoutSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCheckoutSession indicates an expected call of CreateCheckoutSession.
func (mr *MockPayerMockRecorder) CreateCheckoutSession(ctx, params interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckoutSession", reflect.TypeOf((*MockPayer)(nil).CreateCheckoutSession), ctx, params)
}

// UseAPIKey mocks base method.
func (m *MockPayer) UseAPIKey(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseAPIKey", key)
}

// UseAPIKey indicates an expected call of UseAPIKey.
func (mr *MockPayerMockRecorder) UseAPIKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseAPIKey", reflect.TypeOf((*MockPayer)(nil).UseAPIKey), key)
}

// UseToken mocks base method.
func (m *MockPayer) UseToken(accessToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseToken", accessToken)
}

// UseToken indicates an expected call of UseToken.
func (mr *MockPayerMockRecorder) UseToken(accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseToken", reflect.TypeOf((*MockPayer)(nil).UseToken), accessToken)
}
