// Code generated by MockGen. DO NOT EDIT.
// Source: payer.go

// Package checkoutadyen is a generated GoMock package.
package checkoutadyen

import (
	context "context"
	reflect "reflect"

	checkout "github.com/adyen/adyen-go-api-library/v6/src/checkout"
	gomock "go.uber.org/mock/gomock"
)

// MockPayer is a mock of Payer interface.
type MockPayer struct {
	ctrl     *gomock.Controller
	recorder *MockPayerMockRecorder
}

// MockPayerMockRecorder is the mock recorder for MockPayer.
type MockPayerMockRecorder struct {
	mock *MockPayer
}

// NewMockPayer creates a new mock instance.
func NewMockPayer(ctrl *gomock.Controller) *MockPayer {
	mock := &MockPayer{ctrl: ctrl}
	mock.recorder = &MockPayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayer) EXPECT() *MockPayerMockRecorder {
	return m.recorder
}

// CreatePayByLink mocks base method.
func (m *MockPayer) CreatePayByLink(ctx context.Context, req checkout.CreatePaymentLinkRequest) (checkout.PaymentLinkResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayByLink", ctx, req)
	ret0, _ := ret[0].(checkout.PaymentLinkResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayByLink indicates an expected call of CreatePayByLink.
func (mr *MockPayerMockRecorder) CreatePayByLink(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayByLink", reflect.TypeOf((*MockPayer)(nil).CreatePayByLink), ctx, req)
}

// PaymentMethods mocks base method.
func (m *MockPayer) PaymentMethods(ctx context.Context, req checkout.PaymentMethodsRequest) (checkout.PaymentMethodsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaymentMethods", ctx, req)
	ret0, _ := ret[0].(checkout.PaymentMethodsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaymentMethods indicates an expected call of PaymentMethods.
func (mr *MockPayerMockRecorder) PaymentMethods(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaymentMethods", reflect.TypeOf((*MockPayer)(nil).PaymentMethods), ctx, req)
}

// Sessions mocks base method.
func (m *MockPayer) Sessions(ctx context.Context, req checkout.CreateCheckoutSessionRequest) (checkout.CreateCheckoutSessionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sessions", ctx, req)
	ret0, _ := ret[0].(checkout.CreateCheckoutSessionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Sessions indicates an expected call of Sessions.
func (mr *MockPayerMockRecorder) Sessions(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sessions", reflect.TypeOf((*MockPayer)(nil).Sessions), ctx, req)
}

// UseAPIKey mocks base method.
func (m *MockPayer) UseAPIKey(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseAPIKey", key)
}

// UseAPIKey indicates an expected call of UseAPIKey.
func (mr *MockPayerMockRecorder) UseAPIKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseAPIKey", reflect.TypeOf((*MockPayer)(nil).UseAPIKey), key)
}

// UseToken mocks base method.
func (m *MockPayer) UseToken(accessToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseToken", accessToken)
}

// UseToken indicates an expected call of UseToken.
func (mr *MockPayerMockRecorder) UseToken(accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseToken", reflect.TypeOf((*MockPayer)(nil).UseToken), accessToken)
}
