// Code generated by MockGen. DO NOT EDIT.
// Source: payer.go

// Package checkoutmollie is a generated GoMock package.
package checkoutmollie

import (
	context "context"
	reflect "reflect"

	mollie "github.com/VictorAvelar/mollie-api-go/v3/mollie"
	gomock "github.com/golang/mock/gomock"
)

// MockPayer is a mock of Payer interface.
type MockPayer struct {
	ctrl     *gomock.Controller
	recorder *MockPayerMockRecorder
}

// MockPayerMockRecorder is the mock recorder for MockPayer.
type MockPayerMockRecorder struct {
	mock *MockPayer
}

// NewMockPayer creates a new mock instance.
func NewMockPayer(ctrl *gomock.Controller) *MockPayer {
	mock := &MockPayer{ctrl: ctrl}
	mock.recorder = &MockPayerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayer) EXPECT() *MockPayerMockRecorder {
	return m.recorder
}

// CreatePayment mocks base method.
func (m *MockPayer) CreatePayment(ctx context.Context, request mollie.Payment) (mollie.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, request)
	ret0, _ := ret[0].(mollie.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockPayerMockRecorder) CreatePayment(ctx, request interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockPayer)(nil).CreatePayment), ctx, request)
}

// UseAPIKey mocks base method.
func (m *MockPayer) UseAPIKey(key string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseAPIKey", key)
}

// UseAPIKey indicates an expected call of UseAPIKey.
func (mr *MockPayerMockRecorder) UseAPIKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseAPIKey", reflect.TypeOf((*MockPayer)(nil).UseAPIKey), key)
}

// UseToken mocks base method.
func (m *MockPayer) UseToken(accessToken string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UseToken", accessToken)
}

// UseToken indicates an expected call of UseToken.
func (mr *MockPayerMockRecorder) UseToken(accessToken interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UseToken", reflect.TypeOf((*MockPayer)(nil).UseToken), accessToken)
}
