// Code generated by MockGen. DO NOT EDIT.
// Source: oauthClient.go

// Package oauth is a generated GoMock package.
package oauth

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockOauthClient is a mock of OauthClient interface.
type MockOauthClient struct {
	ctrl     *gomock.Controller
	recorder *MockOauthClientMockRecorder
}

// MockOauthClientMockRecorder is the mock recorder for MockOauthClient.
type MockOauthClientMockRecorder struct {
	mock *MockOauthClient
}

// NewMockOauthClient creates a new mock instance.
func NewMockOauthClient(ctrl *gomock.Controller) *MockOauthClient {
	mock := &MockOauthClient{ctrl: ctrl}
	mock.recorder = &MockOauthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOauthClient) EXPECT() *MockOauthClientMockRecorder {
	return m.recorder
}

// ComposeAuthURL mocks base method.
func (m *MockOauthClient) ComposeAuthURL(c context.Context, req ComposeAuthURLRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComposeAuthURL", c, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComposeAuthURL indicates an expected call of ComposeAuthURL.
func (mr *MockOauthClientMockRecorder) ComposeAuthURL(c, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComposeAuthURL", reflect.TypeOf((*MockOauthClient)(nil).ComposeAuthURL), c, req)
}

// GetAccessToken mocks base method.
func (m *MockOauthClient) GetAccessToken(c context.Context, req GetTokenRequest) (GetTokenResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", c, req)
	ret0, _ := ret[0].(GetTokenResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockOauthClientMockRecorder) GetAccessToken(c, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockOauthClient)(nil).GetAccessToken), c, req)
}
