// Code generated by MockGen. DO NOT EDIT.
// Source: api.go

// Package myuuid is a generated GoMock package.
package myuuid

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUUIDer is a mock of UUIDer interface.
type MockUUIDer struct {
	ctrl     *gomock.Controller
	recorder *MockUUIDerMockRecorder
}

// MockUUIDerMockRecorder is the mock recorder for MockUUIDer.
type MockUUIDerMockRecorder struct {
	mock *MockUUIDer
}

// NewMockUUIDer creates a new mock instance.
func NewMockUUIDer(ctrl *gomock.Controller) *MockUUIDer {
	mock := &MockUUIDer{ctrl: ctrl}
	mock.recorder = &MockUUIDerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUUIDer) EXPECT() *MockUUIDerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUUIDer) Create() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create")
	ret0, _ := ret[0].(string)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUUIDerMockRecorder) Create() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUUIDer)(nil).Create))
}
